### ISSUE TITLE
Please update module to be compatible with Puppet 7

### ISSUE THREAD

**Issue by tuxmea** [ipcrm/ipcrm-echo#13]
https://github.com/ipcrm/ipcrm-echo/blob/40d14869094d7be417028c957bf1f06a46329267/metadata.json#L80

**Comment by ipcrm** [comment]
@AFAde resolved this in #15 (thank you!)

**Comment by tuxmea** [comment]
fixed in #15

**Comment by ipcrm** [comment]
@tuxmea version 0.1.8 was published with this change
