### ISSUE TITLE
Feature Request: Allow suppression of resource path in  notification

### ISSUE THREAD

**Issue by ghost** [ipcrm/ipcrm-echo#2]
The current output is
```
Notice: /Echo[TestMessage]/message: Test message
```

It would be nice to be able to do something like...
```
echo {'TestMessage':
  message  => 'Test message',
  withpath => false,
}
```
(using the same `withpath` parameter that `notify` does) and see
```
Notice: Test message
```

I will submit a PR for this.

**Comment by ipcrm** [comment]
Resolved by #4 

Version 0.1.4 (which includes this fix) is published to the forge.  Thx @jearls
