### ISSUE TITLE
Missing 0.1.6 tag

### ISSUE THREAD

**Issue by ragnarkon** [ipcrm/ipcrm-echo#7]
Unfortunately I do not have direct access to the Forge, so I'm reliant on tags to pull down the correct version of Forge modules.

Is it possible to add the `0.1.6` tag to the `61ce5f213951ce40a433fa69e64abb6f7f7aa1e5` commit?  Thanks!

**Comment by gabe-sky** [comment]
Done.  (Also tagged 0.1.4 while I was in there.)  @ragnarkon let me know if it doesn't behave as expected.
